// A suggested time block generated by the scheduling engine
class ScheduleBlockModel {
  final String id;
  final String taskId;
  final String taskTitle;
  final DateTime startTime;
  final DateTime endTime;
  final bool isAiGenerated;
  final String description;

  const ScheduleBlockModel({
    required this.id,
    required this.taskId,
    required this.taskTitle,
    required this.startTime,
    required this.endTime,
    this.isAiGenerated = true,
    this.description = '',
  });

  ScheduleBlockModel copyWith({
    String? id,
    String? taskId,
    String? taskTitle,
    DateTime? startTime,
    DateTime? endTime,
    bool? isAiGenerated,
    String? description,
  }) =>
      ScheduleBlockModel(
        id: id ?? this.id,
        taskId: taskId ?? this.taskId,
        taskTitle: taskTitle ?? this.taskTitle,
        startTime: startTime ?? this.startTime,
        endTime: endTime ?? this.endTime,
        isAiGenerated: isAiGenerated ?? this.isAiGenerated,
        description: description ?? this.description,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'task_id': taskId,
        'task_title': taskTitle,
        'start_time': startTime.toIso8601String(),
        'end_time': endTime.toIso8601String(),
        'is_ai_generated': isAiGenerated,
        'description': description,
      };

  factory ScheduleBlockModel.fromJson(Map<String, dynamic> json) =>
      ScheduleBlockModel(
        id: json['id'] as String? ?? '',
        taskId: json['task_id'] as String? ?? '',
        taskTitle: json['task_title'] as String? ?? 'Study block',
        startTime: DateTime.parse(json['start_time'] as String),
        endTime: DateTime.parse(json['end_time'] as String),
        isAiGenerated: json['is_ai_generated'] as bool? ?? true,
        description: json['description'] as String? ?? '',
      );
}
