// A suggested time block generated by the scheduling engine
class ScheduleBlockModel {
  final String id;
  final String taskId;
  final String taskTitle;
  final DateTime startTime;
  final DateTime endTime;
  final bool isAiGenerated;

  const ScheduleBlockModel({
    required this.id,
    required this.taskId,
    required this.taskTitle,
    required this.startTime,
    required this.endTime,
    this.isAiGenerated = true,
  });
}
